opossum-tool/opossum-file

.github/workflows/lint_and_run_tests.yml
poetry.lock
pyproject.toml

Drop support for python 3.7 to be able to use the latest releases of flake8 and isort
Note: flake8 (6.0.0) requires Python >=3.8.1

drop support for python 3.7

---

poetry.lock
pyproject.toml
src/opossum_lib/graph_generation.py
src/opossum_lib/tree_generation.py
tests/helper_methods.py
tests/test_graph_generation.py
tests/test_tree_generation.py

This PR adds some logic to generate a tree from a given graph. The tests handle three main cases:
- generation of a tree for a graph that contains an undirected cycle
- generation of a tree for a graph that has two components
- generation of a tree for a connected graph where there is not a directed path for each node from the root node of the document. In this case we duplicated the node which "connects" these unreachable nodes with root node and get two trees that are not connected as in the picture below. 
fixes #12

Issue 12 tree generation

---

scripts/linter_and_formatting.sh

While implementing #20 I didn't notice that adding the license header to the linting script did break the script so that it was no longer executable. By adding the license header below the line to make the script executable the script is still executable and reuse compliant.

make script for linting and formatting executable

---

src/opossum_lib/file_generation.py
tests/test_file_generation.py

This PR adds some functionality to add breakpoints in the opossum file. Each folder representing a relationship should be a brekapoint.
This is a subtask of #13.

[issue_13] add breakpoints for nodes that represent a relationship

---

poetry.lock
pyproject.toml
src/opossum_lib/attribution_generation.py
src/opossum_lib/file_generation.py
src/opossum_lib/graph_generation.py
src/opossum_lib/helper_methods.py
src/opossum_lib/opossum_file.py
src/opossum_lib/tree_generation.py
tests/test_attribution_creation.py
tests/test_file_generation.py
tests/test_helper_methods.py
tests/test_opossum_file.py

This PR adds more information to the generated opossum file. We create attributions for each spdx element and link them with the corresponding file path in the resources dict. 
I decided to iterate thorugh all nodes and create the attributions, resources and the linking node by node. This implies the need of a method to merge several nested dicts (`_merge_nested_dict`). I am having some problems with the type hints and mypy here so I decided to disbale type checking here, maybe we can have a look at this together.

Issue 13 add information to resources

---

poetry.lock
src/opossum_lib/attribution_generation.py
src/opossum_lib/cli.py
src/opossum_lib/file_generation.py
src/opossum_lib/graph_generation.py
src/opossum_lib/helper_methods.py
src/opossum_lib/tree_generation.py
tests/helper_methods.py
tests/test_attribution_creation.py
tests/test_cli.py
tests/test_file_generation.py
tests/test_graph_generation.py
tests/test_tree_generation.py

The structure of `tools-python` has changed, so we need to update all import paths and the lock file.

update imports due to changes in upstream package

---

src/opossum_lib/graph_generation.py
tests/test_file_generation.py
tests/test_graph_generation.py

The current implementation in `tools-python` doesn't add labels to the graph, so I decided to keep the previous method and use it as some kind of wrapper and add the labels accordingly. I also updated the tests to check if the labels are set correctly. 
fixes #25

[issue_25] use graph generation from tools-python

---

src/opossum_lib/file_generation.py
tests/data/expected_opossum.json
tests/test_cli.py

This PR fixes the conversion from `OpossumPackage` to dict. As I used the `asdict` method before, the `to_dict()` method of the `Resource` objects wasn't called and the generated output included additional `children` tags. I didn't notice this as we didn't have a test to check the actual output. So, I added a test to check the generated opossum file and fixed the issue. I decided to write a custom `to_dict` method as the `asdict` method from `dataclasses` doesn't allow different `dict_factories` for nested dataclasses. The type hints for this method are rather general to avoid complains from `mypy`. 
#fixes 32

[issue_32] fix conversion to dict

---

src/opossum_lib/attribution_generation.py
src/opossum_lib/constants.py
tests/test_attribution_creation.py

If an SPDX package contains an external reference including a purl we add the locator of the purl to the `packagePURLAppendix` field in the corresponding OpossumPackage. 
part of #41

[issue-41] add purl to OpossumPackage if present in SPDXPackage

---

src/opossum_lib/attribution_generation.py
src/opossum_lib/constants.py
src/opossum_lib/file_generation.py
src/opossum_lib/opossum_file.py
tests/data/expected_opossum.json
tests/test_attribution_creation.py
tests/test_file_generation.py

Similar to the opossum file generated by the Haskell tooling, this PR adds `externalAttributionSources` to label the SPDX elements (file, package or snippet). Previously we added an additional signal for this (as shown in the screenshot below). 
With these changes the SPDXID of each element is no longer visible but instead all packages / files / snippets included in an SPDX element are grouped under "SPDX-Package" / "SPDX-File" / "SPDX_Snippet" in the list of signals (see the screenshot below).

Refactor: Use externalAttributionSources instead of signals to label SPDX elements

---

src/opossum_lib/file_generation.py
src/opossum_lib/merger.py
src/opossum_lib/opossum_file.py
tests/test_cli.py
tests/test_merge.py
tests/test_opossum_file.py

This PR adds a method to merge multiple opossum datastructures. 
In the description of the ticket we said that we want to raise an error if there is a name clash between file and folder when merging resources. So far the implementation doesn't distinguish between file and folder, every leaf in the resource tree is a file. I opened an issue to implement this which should then also take care of the merge functionality (#60).
I decided to implement merge functionalities for all fields currently present in the `OpossumInformation` class. All based on the same principle: merge and deduplicate.
Additionally, I decided to expand the internal IDs for the attributions with the project-id to make them unique per document. As we previously used identical ids for the project I had to adapt the …

[issue-46] Merge opossum datastructures

---

.github/dependabot.yml

This PR adds a basic configuration for dependabot to enable automatic version updates of dependencies. 
fixes #59

[issue-59] add initial configuration for dependabot

---

src/opossum_lib/cli.py
tests/helper_methods.py
tests/test_cli.py

Set a default output file in case no file path is provided. 
We want to enable the user to leave out the output file and write to a default file.
Fix: #56

Add missing output file handling

---

src/opossum_lib/file_generation.py
src/opossum_lib/helper_methods.py
src/opossum_lib/merger.py
src/opossum_lib/opossum_file.py
tests/data/expected_opossum.json
tests/test_file_generation.py
tests/test_helper_methods.py
tests/test_merge.py
tests/test_opossum_file.py

To be able to distinguish files and folder in the resource tree this PR adds a type to the Resource class. When a new element is added to the opossum datastructure the corresponding path is added to the resources with the corresponding ResourceType. Files and snippets get the type FILE, packages FOLDER, the top-level Resource TOP_LEVEL and all other attributions get the type OTHER. Elements within the path get the type FOLDER if they are not yet part of the resource tree. 
I had to delete some parts of the `test_tree_generation_for_bigger_examples` as the introduced changes now result in different expected values (`1` or `{}`) for file paths which doesn't fit with the parametrized tests. As we have other unit tests to verifiy the correctness of the resource tree, I don't think that this …

[issue-60] distinguish file and folder in resource tree

---

src/opossum_lib/file_generation.py
src/opossum_lib/merger.py
src/opossum_lib/opossum_file.py
tests/test_merge.py
tests/test_opossum_file.py

This commit adds a "drop_element" function to the Resource class. As the dataclass is frozen we need to return a new instance of Resource without the specified path. If the specified element has children or if it doesn't exist in the Resource a ValueError is thrown.
fixes #47

[issue-47] Drop element from resource tree

---

.github/workflows/lint_and_run_tests.yml

Disable the fail-fast strategy on matrix elements to ensure that the jobs for ubuntu are run even if the ones for windows or mac fail.
This is a hot fix for issue #69.

[hot-fix] don't cancel matrix jobs if one job fails

---

README.md
pyproject.toml
src/opossum_lib/attribution_generation.py
src/opossum_lib/cli.py
src/opossum_lib/constants.py
src/opossum_lib/file_generation.py
src/opossum_lib/graph_generation.py
src/opossum_lib/helper_methods.py
src/opossum_lib/merger.py
src/opossum_lib/opossum_file.py
src/opossum_lib/tree_generation.py
tests/helper_methods.py
tests/test_attribution_creation.py
tests/test_cli.py
tests/test_file_generation.py
tests/test_graph_generation.py
tests/test_helper_methods.py
tests/test_merge.py
tests/test_opossum_file.py
tests/test_tree_generation.py

Remove date from copyright headers so they don't need to be kept up-to-date.

chore: remove date from copyright header

---

README.md
pyproject.toml
src/opossum_lib/cli.py
tests/test_cli.py

Implements the proposed CLI from #156.
The current CLI is limited to a single SPDX input file. In the future, we want to allow for multiple input files (that then are merged into a single opossum file) and also allow for different input formats such as CycloneDX. To this end the new CLI has options for each allowed input file type (currently only SPDX) and these options can be repeated if multiple files should be input.
As of now neither merging nor other input formats are implemented, so specifying more then 1 SPDX file just raises an error. Failing to provide inputs, also results in an error.
To reflect this new intended functionality the name of the command is changed to `convert2opossum`.
Try one of these commands:
Should work and create a file `output.opossum`
```
uv run opossum-file …
```

feat: new cli

---

src/opossum_lib/opossum/merger.py
src/opossum_lib/opossum/opossum_file.py
src/opossum_lib/scancode/resource_tree.py
src/opossum_lib/spdx/attribution_generation.py
src/opossum_lib/spdx/convert_to_opossum.py
tests/test_opossum/test_merge.py
tests/test_opossum/test_opossum_file.py
tests/test_scancode/test_resource_tree.py
tests/test_spdx/test_attribution_creation.py
tests/test_spdx/test_extract_opossum_information_from_spdx.py

* All classes in opossum_file.py that previously where annotated with `@dataclass` are now based on `pydantic.BaseModel` 
* All constructors of these classes where changed to keywords accordingly
Prior to the introduction of pydantic, Python dataclasses were used. With the switch to validation by pydantic in #172  the path of lowest resistance was chosen which meant switching to pydantic.dataclasses. This PR now completes the migration to pydantic by converting these to `BaseModel`. Apart from being consistent, this enables a much more flexible configuration in the future like e.g. using snake_case for all fields while retaining the correct casing during serialization.

refactor: migrate opossum_file to pydantic basemodel

---

pyproject.toml
src/opossum_lib/opossum/file_generation.py
src/opossum_lib/opossum/merger.py
src/opossum_lib/opossum/opossum_file.py
src/opossum_lib/opossum/output_model.py
src/opossum_lib/scancode/convert_scancode_to_opossum.py
src/opossum_lib/scancode/resource_tree.py
src/opossum_lib/spdx/convert_to_opossum.py
tests/test_opossum/test_file_generation.py
tests/test_opossum/test_merge.py
tests/test_spdx/test_extract_opossum_information_from_spdx.py

* Switched all field names of all models to snake_case adapting the rest of the codebase as necessary
* Enable checking variable naming conventions in ruff's linter
Before the change, the linter would have flagged every field of the Opossum models as camelCase rendering it unusable. After this PR, we now have a consistent naming scheme across the codebase that is enforced by automatic tooling.

Refactor use snake case in models and enable linting

---

README.md
pyproject.toml
uv.lock

Renames the project in the readme and pyproject.toml
As discussed with @mstykow and @Hellgartner, we change the scope of this project to be a more general tool around Opossum files. To this end, the repository will be renamed to `opossum-file`. This PR should be merged directly after the repo is renamed on GitHub.
This PR should be merged after #164 as it's based on that. Merging #165 before this as well is likely easier due to a merge conflict in `pyproject.toml`.

chore: change repository name

---

src/opossum_lib/spdx/attribution_generation.py
src/opossum_lib/spdx/convert_to_opossum.py
src/opossum_lib/spdx/helper_methods.py
tests/data/expected_opossum.json
tests/test_spdx/test_attribution_creation.py
tests/test_spdx/test_extract_opossum_information_from_spdx.py
tests/test_spdx/test_helper_methods.py

* minor changes to attribution_generation.py and helper_methods.py
* convert_to_opossum.py now uses opossum_model.Resource which simplifies the logic
* this caused some tests to change:
- (minor) some tests require a conversion to opossum file format
- resources_to_attribution used to have trailing "/" for folders which are no longer generated. This should have no impact on the validity of the .opossum file
Continuation of #190 
Closes #197 
tests follow separately (tracked by #205 )

feat: change SPDX to the new internal opossum_model

---

.github/workflows/publish-release.yml

renames the artifact build under ubuntu from `opossum-file-for-ubuntu` to `opossum-file-for-linux`.
This change requires changing the [installer script in OpossumUI](https://github.com/opossum-tool/OpossumUI/blob/3f12f10a9ab93720155c17977d76abe7e458a0f5/package.json#L148) accordingly.

chore: rename linux build

---

.github/workflows/publish-release.yml

Adjusted publish-release.yml to build and publish opossum-file executables for both Intel and ARM64 architecture based MacOS systems.
Can be tested by creating a temporary pre-release based on this branch.

Publish two MacOS executables on release

---

src/opossum_lib/core/entities/scan_results.py
src/opossum_lib/input_formats/opossum/services/convert_to_opossum.py
tests/conftest.py
tests/core/entities/generators/scan_results_provider.py
tests/core/entities/test_opossum.py
tests/setup/opossum_faker_setup.py
tests/setup/opossum_file_faker_setup.py
tests/setup/scancode_faker_setup.py

* changes the seeding of Faker to guarantee a random seed for every run
The strength of Faker is the random generation of valid inputs. With a fixed seed this advantage is lost. For incomprehensible reasons, there was no randomization taking place. This PR fixes that be altering the setup slightly.
Dump a few generated documents, e.g. by putting this snippet:
```python
def test_generate(scancode_faker: ScanCodeFaker) -> None:
scancode_data = scancode_faker.scancode_data()
seed = int(datetime.now().timestamp())
with open(f"generated_scancode-{seed}.json", "w") as out:
out.write(scancode_data.model_dump_json(indent=4))
```
at the end of `tests/input_formats/scancode/services/test_convert_to_opossum.py` and running it a couple of times.
Before this change, this yields identical files. After …

fix: Faker seed should be random

---

tests/setup/opossum_faker_setup.py
tests/setup/opossum_file_faker_setup.py
tests/setup/scancode_faker_setup.py

Simplify the Faker type definitions:
* remove unused class attributes
* reduce the constructors to bare minimum (they are never executed anyhow)
* remove internal providers from instance variables (they are not accessible in the tests)
* add missing providers and their methods
* add comment explaining the purpose of these classes
We use these classes to help the IDE know which methods are available on the Faker instance in the tests and also to communicate that information to mypy. As such these classes are neither used nor instanced and can be kept to a bare minimum. 
There should be no functional difference. Code completion for methods of specific Faker types in the test should still work. Mypy should not raise any concerns.

Cleanup the Faker class stubs

---

src/opossum_lib/core/entities/resource.py
src/opossum_lib/core/entities/root_resource.py
src/opossum_lib/core/entities/scan_results.py
src/opossum_lib/core/services/merge_opossums.py
src/opossum_lib/input_formats/opossum/services/convert_to_opossum.py
src/opossum_lib/input_formats/scancode/services/convert_to_opossum.py
tests/core/entities/generators/resource_provider.py
tests/core/entities/generators/scan_results_provider.py
tests/core/entities/test_opossum.py
tests/core/services/test_merge_opossums.py
tests/input_formats/scancode/services/test_convert_to_opossum.py
tests/input_formats/scancode/services/test_get_attribution_info.py

This PR introduces `RootResource` as new model to replace `list[Resource]` as the type of `ScanResults.resources`.
This new model handles:
* insertion of new `Resources`
* iterating of all `Resources`
Thus it serves to simplify some reoccuring logic aorund the codebase:
* iteration replaces recursive function in `create_attribution_mapping`, `_merge_resources` and in `test_convert_to_opossum.py` (scancode)
* `temp_root` construct removed from `_extract_opossum_resources`, `_merge_resources`
Minor change:
* eliminated `_convert_path_to_str` in favor of `Path`'s `.as_posix()`
During writing the `merge_opossums` I noticed that I started to repeat code that I had already written before. This PR aims to introduce an abstraction layer to clean that up. It is expected that this also helps future …

refactor: introduce RootResource

---

src/opossum_lib/core/entities/root_resource.py
src/opossum_lib/core/entities/scan_results.py

* OpossumUI always assumes that the resources' paths are relative, i.e. there is no root folder named "/"
* Thus the RootResource enforces this when using `add_resource`
Opening a file produced by the OWASP converter in OpossumUI shows a weird file structure: There are 3 nested root folders, i.e. folders named `"/"` before the filetree begins and the attributions are not attached to their files. The root (pun intended) of this problem is that the paths from OWASP are given in absolute form, i.e. starting with "/". 
This PR fixes this problem once and for by enforcing a consistent normalization of paths done by the RootResource. Every `Resource` added to a `RootResource` by means of `add_resource` has its path stripped of any root. This guarantees that the resulting file will never look …

feat: RootResource normalizes paths

---

.pre-commit-config.yaml

Add the dependencies from the `project.toml` also to the `pre-commit-config.yaml`.
Goal: Make mypy behavior of precommit scans and cli runs the same
Context: Pre-commit mypy runs in a dedicated venv which by default does not get the project's dependencies. This leads to differing behavior between the pre-commit hook and the cli runs
Possible caveat: We now need to maintain the dependencies at two places. However, this should be taken care of by renovate

Add mypy precommit dependencies

---

.pre-commit-config.yaml
pyproject.toml
src/opossum_lib/input_formats/owasp_dependency_scan/services/convert_to_opossum.py
tests/core/entities/test_opossum.py
tests/input_formats/owasp_dependency_scan/entities/generators/owasp_dependency_report_model_provider.py
tests/input_formats/owasp_dependency_scan/services/test_convert_to_opossum.py
tests/shared/generator_helpers.py
uv.lock

* Correctly set path dependent on whether a dependency is virtual or not
* No longer add attributions if there are neither packages nor evidences
* Add all virtual dependencies to the files with children

Improvements of OWASP conversion
